runtime: nodejs20
service: frontend
env: standard

handlers:
  # Serve static files
  - url: /static
    static_dir: dist/static
    secure: always

  # Serve other static assets
  - url: /(.*\.(json|ico|js|png|txt|css))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js|png|txt|css)$
    secure: always

  # All other requests go to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

env_variables:
  REACT_APP_API_URL: "https://api.smart-recipe-hub.appspot.com"  # Replace with your API service URL
  NODE_ENV: "production"
  VITE_CLERK_PUBLISHABLE_KEY: "pk_test_a2Vlbi1icmVhbS0yNS5jbGVyay5hY2NvdW50cy5kZXYk"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  target_throughput_utilization: 0.6