runtime: nodejs18
service: api
env: standard

entrypoint: node src/server.js

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: "production"
  CORS_ORIGIN: "https://smart-recipe-hub-444400.uc.r.appspot.com/"
  GEMINI_LINK: "${GEMINI_LINK}"
  MONGO_URI: "${MONGO_URI}"
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Configure logging
runtime_config:
  operating_system: "ubuntu22"
  enable_stackdriver_integration: true
